# Generated by Django 4.2.5 on 2023-09-26 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_is_ative_product_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
    ]
